# version: '2.4'
# versions no longer needed for compose CLI use (as of 2020)

services:

  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command:
      - /bin/sh
      - -c
      - |
        ../node_modules/typescript/bin/tsc -p .
        ../node_modules/.bin/nodemon --inspect=0.0.0.0:8080 ./bin/www
    ports:
      - "80:80"
      - "8080:8080"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/opt/node_app/app
      - ./package.json:/opt/node_app/package.json
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development
      - PGADMIN_DEFAULT_EMAIL="root@email.com"
      - PGADMIN_DEFAULT_PASSWORD="copa2022!"
    links:
      - "postgres:postgresdb"
    depends_on:
      - postgres
    healthcheck:
      disable: true
    networks:
      - node-with-postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@email.com"
      PGADMIN_DEFAULT_PASSWORD: "copa2022!"
    ports:
      - "8008:80"
    depends_on:
      - postgres
    networks:
      - node-with-postgres
    links:
      - "postgres:postgresdb"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "copa2022!"
      POSTGRES_USER: "root"
    ports:
      - "5432:5432"
    networks:
      - node-with-postgres

volumes:
  notused:

networks: 
  node-with-postgres:
    driver: bridge
